apiVersion: v1
kind: Namespace
metadata:
  name: kdeploy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kdeploy
automountServiceAccountToken: true
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kdeploy
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "namespaces", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kdeploy-binding
  namespace: graphik-system
subjects:
  - kind: ServiceAccount
    name: kdeploy
roleRef:
  kind: Role
  name: kdeploy
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: kdeploy
  namespace: graphik-system
  labels:
    app: kdeploy
spec:
  ports:
  - port: 8820
    name: api
  - port: 8821
    name: admin
  clusterIP: None
  selector:
    app: kdeploy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdeploy
  namespace: graphik-system
spec:
  serviceName: kdeploy
  serviceAccountName: kdeploy
  replicas: 1
  selector:
    matchLabels:
      app: kdeploy
  template:
    metadata:
      labels:
        app: kdeploy
    spec:
      containers:
        - name: kdeploy
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: graphikdb/kdeploy:v0.0.0
          imagePullPolicy: Always
          ports:
          - containerPort: 8821
          - containerPort: 8820

